### ISSUE TITLE
Libraries folder broken/not correctly in repo

### ISSUE THREAD

**Issue by niko20010** [HackerspaceBremen/hshb-tuerschild#1]
The "lib" folder in the arduino folder seems to be a symlink to a location outside of the repo on your local machine.
screenshot here:
![bildschirmfoto15](https://cloud.githubusercontent.com/assets/6323639/14230854/1371391e-f96b-11e5-8195-fbef1c5a8668.png)

**Comment by Syralist** [comment]
That's true. I don't know how to fix it right now, but I will look into it.

**Comment by Syralist** [comment]
I deleted the symlink and added the libraries as a submodule.
Right now the repo linked in the submodule contains all my libs. Next step would be to create a branch with only the necessary libs for this project.
